
elasticsearch:
  image: elasticsearch:1.6
  hostname: es
  domainname: data.deepcarbon.net
  ports:
  - "0.0.0.0:49200:9200"
  volumes:
  - config:/usr/share/elasticsearch/config:ro
  - /data/elasticsearch:/usr/share/elasticsearch/data
  restart: on-failure:3

search:
  image: nginx
  hostname: facets
  domainname: info.deepcarbon.net
  ports:
  - "0.0.0.0:49157:80"
  - "0.0.0.0:49158:443"
  volumes:
  - html:/usr/share/nginx/html/browsers2:ro
  restart: on-failure:3
